#ifndef PWM_DRIVER 
#define PWM_DRIVER

#include "board.h"
#include <motor_module.h>
#include <asf.h>

 // Test function for PWM Module
void test_pwm(void);

// configure io ports and master clock for pwm module
void configure_pwm(void);

// attach motor to pwm channel specified by motor
void attach_motor(Motor *m);

// Updates duty cycle generated by channel
void update_duty_cycle(uint32_t duty_cycle, Channel chan);
#endif