#ifndef PWM_DRIVER 
#define PWM_DRIVER

#include "board.h"
#include <motor_module.h>
#include <asf.h>

pwm_channel_t pwm_0;
pwm_channel_t pwm_1;
pwm_channel_t pwm_2;
pwm_channel_t pwm_3;

 // Test function for PWM Module
void test_pwm(void);

// configure io ports and master clock for pwm module
void configure_pwm(void);

// Updates duty cycle generated by channel
void update_duty_cycle(uint32_t duty_cycle, Channel chan);

#endif