#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Sat Apr 17 13:46:59 PDT 2021
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 0f2c5dbfef4149a597af3ddb0f18050a --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot clk_to_pwm_tb_behav xil_defaultlib.clk_to_pwm_tb xil_defaultlib.glbl -log elaborate.log"
xelab -wto 0f2c5dbfef4149a597af3ddb0f18050a --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot clk_to_pwm_tb_behav xil_defaultlib.clk_to_pwm_tb xil_defaultlib.glbl -log elaborate.log

