#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sat Apr 17 13:45:38 PDT 2021
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim clk_to_pwm_tb_behav -key {Behavioral:sim_1:Functional:clk_to_pwm_tb} -tclbatch clk_to_pwm_tb.tcl -log simulate.log"
xsim clk_to_pwm_tb_behav -key {Behavioral:sim_1:Functional:clk_to_pwm_tb} -tclbatch clk_to_pwm_tb.tcl -log simulate.log

